version: '3'

services:
  discord-bot:
    container_name: discord-bot
    build: .
    image: discord-bot
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/usr/src/app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.backend=nodelol-discord-bot"
      - "traefik.port=80"
      - "traefik.port=443"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - web

networks:
  web:
    external: true
